services:
  backend:
    image: frappe/erpnext:v15.41.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /mnt/erpnext_data/sites:/home/frappe/frappe-bench/sites  # Mount EBS volume to sites
      - /mnt/erpnext_data/logs:/home/frappe/frappe-bench/logs # Mount EBS volume for logs

  configurator:
    image: frappe/erpnext:v15.41.2
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - /mnt/erpnext_data/sites:/home/frappe/frappe-bench/sites  # Mount EBS volume to sites
      - /mnt/erpnext_data/logs:/home/frappe/frappe-bench/logs # Mount EBS volume for logs

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - /mnt/erpnext_data/db-data:/var/lib/mysql  # Bind EBS volume for db-data

  redis-queue:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /mnt/erpnext_data/redis-queue-data:/data  # Bind EBS volume for Redis queue

  redis-cache:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /mnt/erpnext_data/redis-cache-data:/data  # Bind EBS volume for Redis cache

  frontend:
    image: frappe/erpnext:v15.41.2
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: qodexcore
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - /mnt/erpnext_data/sites:/home/frappe/frappe-bench/sites  # Bind EBS volume to sites
      - /mnt/erpnext_data/logs:/home/frappe/frappe-bench/logs  # Bind EBS volume for logs
    ports:
      - "8080:8080"

  queue-long:
    image: frappe/erpnext:v15.41.2
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - /mnt/erpnext_data/sites:/home/frappe/frappe-bench/sites  # Bind EBS volume to sites
      - /mnt/erpnext_data/logs:/home/frappe/frappe-bench/logs  # Bind EBS volume for logs

  queue-short:
    image: frappe/erpnext:v15.41.2
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - /mnt/erpnext_data/sites:/home/frappe/frappe-bench/sites  # Bind EBS volume to sites
      - /mnt/erpnext_data/logs:/home/frappe/frappe-bench/logs  # Bind EBS volume for logs

  scheduler:
    image: frappe/erpnext:v15.41.2
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - /mnt/erpnext_data/sites:/home/frappe/frappe-bench/sites  # Bind EBS volume to sites
      - /mnt/erpnext_data/logs:/home/frappe/frappe-bench/logs  # Bind EBS volume for logs

  websocket:
    image: frappe/erpnext:v15.41.2
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - /mnt/erpnext_data/sites:/home/frappe/frappe-bench/sites  # Bind EBS volume to sites
      - /mnt/erpnext_data/logs:/home/frappe/frappe-bench/logs  # Bind EBS volume for logs

# volumes:
#   db-data:
#   redis-queue-data:
#   redis-cache-data:
#   sites:
#   logs:
